version: "3.9"

services:
  postgres:
    image: postgres:15
    container_name: postgres
    ports:
      - "5433:5433"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 23032006yj
      POSTGRES_DB: dodo_pizza_base
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - pizza-network

  fergana:
    build: ./fergana
    container_name: fergana
    ports:
      - "7004:7004"
    depends_on:
      - postgres
    networks:
      - pizza-network

  order:
    build: ./order
    container_name: order
    ports:
      - "7003:7003"
    depends_on:
      - postgres
    networks:
      - pizza-network

  gateway:
    build: ./gateway
    container_name: gateway
    ports:
      - "3000:3000"
    depends_on:
      - fergana
      - order
    networks:
      - pizza-network

volumes:
  pgdata:

networks:
  pizza-network:
