
services:
  fergana:
    build: ./fergana
    container_name: fergana
    ports:
      - "7004:7004"
    networks:
      - pizza-network

  order:
    build: ./order
    container_name: order
    ports:
      - "7003:7003"
    networks:
      - pizza-network

  gateway:
    build: ./gateway
    container_name: gateway
    ports:
      - "3000:3000"
    networks:
      - pizza-network
    depends_on:
      - fergana
      - order

networks:
  pizza-network:
