version: "3.9"

services:
  fergana:
    build: ./fergana
    container_name: fergana
    ports:
      - "7004:7004"
    depends_on:
      - gateway
    extra_hosts:
      - "host.docker.internal:172.17.0.1"
    networks:
      - pizza-network

  order:
    build: ./order
    container_name: order
    ports:
      - "7003:7003"
    depends_on:
      - gateway
    extra_hosts:
      - "host.docker.internal:172.17.0.1"
    networks:
      - pizza-network

  gateway:
    build: ./gateway
    container_name: gateway
    ports:
      - "3000:3000"
    extra_hosts:
      - "host.docker.internal:172.17.0.1"
    networks:
      - pizza-network

networks:
  pizza-network:
