services:
  db:
    image: postgres:14
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 23032006yj
      POSTGRES_DB: dodo_pizza_base
    volumes:
      - postgres_data:/var/lib/postgresql/data

  gateway:
    build: ./gateway
    ports:
      - "3000:3000"
    depends_on:
      - db

  order:
    build: ./order
    ports:
      - "3001:3001"
    depends_on:
      - db

  fergana:
    build: ./fergana
    ports:
      - "3002:3002"
    depends_on:
      - db

volumes:
  postgres_data:
