version: '3.8'

services:
  fergana:
    build: ./fergana
    container_name: fergana
    ports:
      - "7004:7004"
    networks:
      - pizza-network
    depends_on:
      - postgres

  order:
    build: ./order
    container_name: order
    ports:
      - "7003:7003"
    networks:
      - pizza-network
    depends_on:
      - postgres

  gateway:
    build: ./gateway
    container_name: gateway
    ports:
      - "3000:3000"
    networks:
      - pizza-network
    depends_on:
      - fergana
      - order

  postgres:
    image: postgres:15
    container_name: postgres
    restart: always
    environment:
      POSTGRES_DB: dodo_pizza_base
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 23032006yj
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - pizza-network

volumes:
  pgdata:

networks:
  pizza-network:
