export const BOT_SERVICE = "BOT_SERVICE"
export const PROFILE_SERVICE = "PROFILE_SERVICE"
export const PRODUCT_SERVICE_TOPPING_MODULE = "PRODUCT_SERVICE_TOPPING_MODULE"
export const PRODUCT_SERVICE_PIZZA_MODULE = "PRODUCT_SERVICE_PIZZA_MODULE"